# frozen_string_literal: true

require "bundler/gem_helper"
require "fileutils"
require "minitar"
require "open-uri"
require "os"
require "rake/clean"
require "rake/testtask"
require "tempfile"

import "../rakelib/file_tools.rake"

Bundler::GemHelper.install_tasks

CLEAN.include("build")
CLOBBER.include("bundled", "cmd/bundled", "generated", "pkg")

GATEWAY_VERSION = Bundler::GemHelper.gemspec.version.to_s[%r{^\d(?:\.\d+)+}]

BASE_URL = URI("https://github.com/grpc-ecosystem/grpc-gateway/releases/download/v#{GATEWAY_VERSION}/")

BINARIES = {
  "protoc-gen-grpc-gateway-v#{GATEWAY_VERSION}-darwin-x86_64" => "protoc-gen-grpc-gateway-darwin-x86_64",
  "protoc-gen-grpc-gateway-v#{GATEWAY_VERSION}-linux-x86_64" => "protoc-gen-grpc-gateway-linux-x86_64",
  "protoc-gen-grpc-gateway.exe-v#{GATEWAY_VERSION}-windows-x86_64.exe" => "protoc-gen-grpc-gateway-windows-x86_64.exe",
  "protoc-gen-swagger-v#{GATEWAY_VERSION}-darwin-x86_64" => "protoc-gen-swagger-darwin-x86_64",
  "protoc-gen-swagger-v#{GATEWAY_VERSION}-linux-x86_64" => "protoc-gen-swagger-linux-x86_64",
  "protoc-gen-swagger.exe-v#{GATEWAY_VERSION}-windows-x86_64.exe" => "protoc-gen-swagger-windows-x86_64.exe",
}.freeze

desc "Download plugin binaries"
task "download" do
  # Download grpc-gateway license
  FileTools.download(
    source: "https://raw.githubusercontent.com/grpc-ecosystem/grpc-gateway/v#{GATEWAY_VERSION}/LICENSE.txt",
    target: "LICENSE-grpc-gateway.txt"
  )

  # Download binaries
  BINARIES.each do |source_name, target_name|
    FileTools.download(
      source: URI.join(BASE_URL, source_name),
      target: "cmd/bundled/#{target_name}",
      mode: %r{-(darwin|linux)-x86_64} =~ target_name ? 0o755 : nil
    )
  end
end

file "LICENSE.txt" => "../../LICENSE.txt" do |file|
  FileUtils.cp(file.prerequisites.first, file.name)
end

task "build" => %w[download LICENSE.txt]

Rake::TestTask.new("test" => "download") do |t|
  t.libs = %w[lib test]
  t.test_files = Dir["test/**/*_test.rb"]
end
