#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.append(File.join(__dir__), "lib")

require "protoc/tools/core_extensions"

using Protoc::Tools::CoreExtensions

prog = Gem.platform_bin_name(name: "#{__dir__}/bundled/protoc")
exec(prog, *ARGV)
