# frozen_string_literal: true

require "bundler/setup"

require "bundler/gem_helper"
require "fileutils"
require "grpc/gateway/protoc/grpc_gateway_output"
require "grpc/gateway/protoc/swagger_output"
require "protoc/tools/protoc/output/grpc_ruby_output"
require "protoc/tools/protoc/output/ruby_output"
require "rake/clean"

CLEAN.include("build")
CLOBBER.include("bundled", "generated", "pkg")

Bundler::GemHelper.install_tasks

PROTO_FILES = Dir["**/*.proto", base: "proto"]

namespace "proto" do
  desc "Generate Ruby code from proto files"
  task "generate" do
    protoc = Protoc::Tools::Protoc::Compiler.new do
      ruby_out
      grpc_ruby_out
    end
    protoc.run(base_dirs: "proto", files: PROTO_FILES)
  end
end

namespace "swagger" do
  desc "Generate Swagger documentation from proto files"
  task "generate" do
    protoc = Protoc::Tools::Protoc::Compiler.new do
      swagger_out
    end
    protoc.run(base_dirs: "proto", files: PROTO_FILES)
  end
end

namespace "gateway" do
  desc "Generate GRPC gateway code from proto files"
  task "generate" do
    protoc = Protoc::Tools::Protoc::Compiler.new do
      grpc_gateway_out
    end
    protoc.run(base_dirs: "proto", files: PROTO_FILES)
  end
end

file "LICENSE.txt" => "../../../LICENSE.txt" do |file|
  FileUtils.cp(file.prerequisites.first, file.name)
end

desc "Generate all code and documentation from proto files"
task "generate" => %w[proto:generate swagger:generate gateway:generate]

task "build" => %w[generate LICENSE.txt]
