# frozen_string_literal: true

require "bundler/setup"

require "bundler/gem_helper"
require "fileutils"
require "grpc/gateway/protoc/grpc_gateway_output"
require "grpc/gateway/protoc/swagger_output"
require "protoc/tools/protoc_task"
require "rake/clean"
require "rake/testtask"

CLEAN.include("build")
CLOBBER.include("bundled", "generated", "pkg")

Bundler::GemHelper.install_tasks

PROTO_FILES = Dir["**/*.proto", base: "proto"]

namespace "proto" do
  desc "Generate Ruby code from proto files"
  Protoc::Tools::ProtocTask.new(name: "generate") do
    protoc { ruby_out; grpc_ruby_out }
    proto_files PROTO_FILES
  end
end

namespace "swagger" do
  desc "Generate Swagger documentation from proto files"
  Protoc::Tools::ProtocTask.new(name: "generate") do
    protoc { swagger_out }
    proto_files PROTO_FILES
  end
end

namespace "gateway" do
  desc "Generate GRPC gateway code from proto files"
  Protoc::Tools::ProtocTask.new(name: "generate") do
    protoc { grpc_gateway_out }
    proto_files PROTO_FILES
  end
end

file "LICENSE.txt" => "../../../LICENSE.txt" do |file|
  FileUtils.cp(file.prerequisites.first, file.name)
end

desc "Generate all code and documentation from proto files"
task "generate" => %w[proto:generate swagger:generate gateway:generate]

task "build" => %w[generate LICENSE.txt]

Rake::TestTask.new("test" => "generate") do |t|
  t.libs = %w[lib test]
  t.test_files = Dir["test/**/*_test.rb"]
end
