AllCops:
  TargetRubyVersion: 2.6

Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: true

Layout/DefEndAlignment:
  AutoCorrect: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Max: 120

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/Void:
  Exclude:
    - "test/**/*"

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: line_count_based

Style/CommandLiteral:
  EnforcedStyle: percent_x

Style/FrozenStringLiteralComment:
  EnforcedStyle: always_true

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: false

Style/Next:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
