#!/usr/bin/env ruby
# frozen_string_literal: true

require "protoc/tools/gem_extensions"

using Protoc::Tools::GemExtensions

prog = Gem.platform_bin_name(name: "#{__dir__}/bundled/protoc-gen-swagger")
exec(prog, *ARGV)
