#!/usr/bin/env ruby
# frozen_string_literal: true

require "protoc/tools/standard_extensions"

using Protoc::Tools::StandardExtensions

prog = Gem.platform_bin_name(name: "#{__dir__}/bundled/protoc-gen-grpc-gateway")
exec(prog, *ARGV)
