# frozen_string_literal: true

require "bundler/gem_helper"
require "fileutils"
require "minitar"
require "open-uri"
require "os"
require "protoc/tools/protoc_task"
require "rake/clean"
require "rake/testtask"
require "tempfile"
require "zlib"

import "../rakelib/file_tools.rake"

CLEAN.include("build")
CLOBBER.include("bundled", "generated", "pkg")

Bundler::GemHelper.install_tasks

GATEWAY_VERSION = Bundler::GemHelper.gemspec.version.to_s.to_s[%r{^\d(?:\.\d+)+}]

SOURCE_URL = URI("https://github.com/grpc-ecosystem/grpc-gateway/archive/v#{GATEWAY_VERSION}.tar.gz")

PROTO_FILES_REGEX = %r{/((?:protoc-gen-swagger/options|google(?:/[^/]+))/[^/]+\.proto)$}.freeze

desc "Download grpc-tools source code"
task "download" do
  # Download grpc-gateway license
  FileTools.download(
    source: "https://raw.githubusercontent.com/grpc-ecosystem/grpc-gateway/v#{GATEWAY_VERSION}/LICENSE.txt",
    target: "LICENSE-grpc-gateway.txt"
  )

  # Download source archive
  FileTools.download_tar_archive(source: SOURCE_URL) do |entry|
    File.join("bundled/proto", Regexp.last_match(1)) if PROTO_FILES_REGEX =~ entry.full_name
  end
end

desc "Generate Ruby code from proto files"
task "generate" => "download" do
  Protoc::Tools::ProtocTask.new(name: "generate") do
    protoc { ruby_out; grpc_ruby_out; proto_dirs "bundled/proto" }
    proto_files Dir["**/*.proto", base: "bundled/proto"]
  end
end

file "LICENSE.txt" => "../../LICENSE.txt" do |file|
  FileUtils.cp(file.prerequisites.first, file.name)
end

task "build" => %w[generate LICENSE.txt]

Rake::TestTask.new("test" => "generate") do |t|
  t.libs = %w[lib test]
  t.test_files = Dir["test/**/*_test.rb"]
end
