name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - name: Install bundler
        run: gem install bundler
        working-directory: ruby/protoc-tools
      - name: Test and install ruby/protoc-tools
        run: bundle install --quiet && bundle exec rake test install:local
        working-directory: ruby/protoc-tools
      - name: Test and install ruby/protoc-grpc-gateway-options
        run: bundle install --quiet && bundle exec rake test install:local
        working-directory: ruby/protoc-grpc-gateway-options
      - name: Test and install ruby/protoc-grpc-gateway-plugins
        run: bundle install --quiet && bundle exec rake test install:local
        working-directory: ruby/protoc-grpc-gateway-plugins
